<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">
    <img src="./images/bookbooking.png">
    </a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"><i class="fa-solid fa-book"></i> &nbsp;&nbsp;  Home</a>
        </li>
                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"><i class="fas fa-layer-group"></i> &nbsp;&nbsp;  Categorie</a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"> <i class="fa-solid fa-user"></i> &nbsp;&nbsp;  Auteur</a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"><i class="fa-solid fa-address-card"></i> &nbsp;&nbsp; Frofil</a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
        
        
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"></a>
        </li>
                        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"> Ar</a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"> | Fr | </a>
        </li>
                                <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"> Ag</a>
        </li>
      </ul>

    </div>
  </div>
</nav>